# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Sn2
tagline:             'Lamentations on iOS'
description:         'Odds and ends that worked'
url:                 http://sntwo.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Josh Knapp
  url:               
  email:             joshk1225@yahoo.com

# Custom vars
version:             1.0.0
